version: "3.4"

services:
  pgdb:
    image: postgres
    restart: unless-stopped
    env_file:
      - ./metabase/config/postgres_exemple.env

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - pgdb

volumes:
  postgres_db_data: